CREATE SEQUENCE order_number_seq START WITH 100000 INCREMENT BY 1;

CREATE TABLE pizza (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)   NOT NULL,
    description VARCHAR(1000),
    price       NUMERIC(10, 2) NOT NULL,
    image_path  VARCHAR(500),
    active      BOOLEAN        NOT NULL DEFAULT TRUE,
    sort_order  INTEGER        NOT NULL DEFAULT 0
);

CREATE TABLE topping (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)   NOT NULL,
    description VARCHAR(1000),
    price       NUMERIC(10, 2) NOT NULL,
    active      BOOLEAN        NOT NULL DEFAULT TRUE
);

CREATE TABLE pizza_topping (
    pizza_id   BIGINT NOT NULL REFERENCES pizza (id),
    topping_id BIGINT NOT NULL REFERENCES topping (id),
    PRIMARY KEY (pizza_id, topping_id)
);

CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number   BIGINT         NOT NULL UNIQUE,
    created_at     TIMESTAMP      NOT NULL,
    status         VARCHAR(20)    NOT NULL,
    order_type     VARCHAR(20)    NOT NULL,
    payment_status VARCHAR(20)    NOT NULL,
    first_name     VARCHAR(255)   NOT NULL,
    last_name      VARCHAR(255)   NOT NULL,
    phone          VARCHAR(50)    NOT NULL,
    email          VARCHAR(255)   NOT NULL,
    street         VARCHAR(255),
    house_number   VARCHAR(20),
    postal_code    VARCHAR(20),
    city           VARCHAR(255),
    total_price    NUMERIC(10, 2) NOT NULL
);

CREATE TABLE order_item (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT         NOT NULL REFERENCES orders (id),
    pizza_id         BIGINT         NOT NULL REFERENCES pizza (id),
    quantity         INTEGER        NOT NULL,
    base_price       NUMERIC(10, 2) NOT NULL,
    item_total_price NUMERIC(10, 2) NOT NULL
);

CREATE TABLE order_item_topping (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id  BIGINT         NOT NULL REFERENCES order_item (id),
    topping_id     BIGINT         NOT NULL REFERENCES topping (id),
    topping_name   VARCHAR(255)   NOT NULL,
    topping_price  NUMERIC(10, 2) NOT NULL
);
